<script lang="ts">
  import { onMount } from "svelte";
  import { getSupabaseContext } from "$lib/supabase/context";
  import "$styles/components/editorial.css";

  // ── session / role guard ────────────────────────────────────────────────
  const { supabase, session } = getSupabaseContext();
  let role: "user" | "mod" | "admin" = "user";
  let roleChecked = false;

  async function checkRole() {
    if (!session?.user?.id) { role = "user"; roleChecked = true; return; }
    const { data } = await supabase.from("profiles").select("role").eq("id", session.user.id).single();
    role = ((data as any)?.role ?? "user") as typeof role;
    roleChecked = true;
  }
  onMount(checkRole);

  // ── grid state ──────────────────────────────────────────────────────────
  type Row = {
    path: string;          // local filesystem path on the admin's machine
    name: string;
    year: string;
    collection: string;
    map_type: string;
    location: string;
    // computed after create
    id?: string;
    status?: "pending" | "created" | "failed";
    error?: string;
  };

  const blankRow = (): Row => ({ path: "", name: "", year: "", collection: defaultCollection, map_type: "topographic", location: "" });

  let defaultCollection = "Service Géographique de l'Indochine";
  let rows: Row[] = [blankRow()];
  let creating = false;
  let resultScript = "";
  let createSummary = "";

  function addRow() { rows = [...rows, blankRow()]; }
  function removeRow(i: number) { rows = rows.filter((_, j) => j !== i); if (rows.length === 0) addRow(); }
  function clearAll() { rows = [blankRow()]; resultScript = ""; createSummary = ""; }

  // ── Paste parser: accepts tab-separated, CSV, or simple "path" lists ───
  // Tries to be forgiving. If the line has tabs, splits on tab. If it has
  // commas and looks like CSV, splits on comma. Otherwise treats whole line
  // as path and tries to auto-parse name/year from the filename.
  function parsePaste(text: string) {
    const lines = text.split(/\r?\n/).map(l => l.trim()).filter(Boolean);
    const parsed: Row[] = [];
    for (const line of lines) {
      let cells: string[];
      if (line.includes("\t")) cells = line.split("\t");
      else if (line.split(",").length >= 3) cells = line.split(",");
      else cells = [line];

      const [path = "", name0 = "", year0 = "", collection0 = "", map_type0 = "", location0 = ""] = cells.map(s => s.trim());
      const auto = autoFromFilename(path);
      parsed.push({
        path,
        name: name0 || auto.name,
        year: year0 || auto.year,
        collection: collection0 || defaultCollection,
        map_type: map_type0 || "topographic",
        location: location0,
      });
    }
    if (parsed.length) rows = parsed;
  }

  function autoFromFilename(path: string): { name: string; year: string } {
    if (!path) return { name: "", year: "" };
    const base = path.split("/").pop()?.replace(/\.[^.]+$/, "") ?? "";
    const yearMatch = base.match(/(\d{4})\s*$/);
    const year = yearMatch ? yearMatch[1] : "";
    let name = year ? base.slice(0, yearMatch!.index).trim() : base;
    // Drop leading "<sheet#> " prefix (e.g. "20 Ha Noi" → "Ha Noi")
    name = name.replace(/^\d+[a-z]?\.?\s+/, "").trim();
    return { name, year };
  }

  function applyAutoName(i: number) {
    const auto = autoFromFilename(rows[i].path);
    rows[i] = { ...rows[i], name: auto.name || rows[i].name, year: auto.year || rows[i].year };
    rows = rows;
  }

  // ── Create batch ─────────────────────────────────────────────────────────
  async function createBatch() {
    creating = true;
    createSummary = "";
    let okCount = 0, failCount = 0;
    const cmds: string[] = [
      "#!/usr/bin/env bash",
      "# Generated by /admin/bulk — run from the svelte-beta repo root.",
      "set -euo pipefail",
      "cd \"$(dirname \"$0\")\"",
      "",
    ];

    for (let i = 0; i < rows.length; i++) {
      const r = rows[i];
      if (!r.path.trim() || !r.name.trim()) {
        rows[i] = { ...r, status: "failed", error: "path and name required" };
        failCount++; continue;
      }
      try {
        const payload: any = {
          name: r.name.trim(),
          year: r.year ? Number(r.year) : null,
          collection: r.collection.trim() || null,
          map_type: r.map_type.trim() || null,
          location: r.location.trim() || null,
          source_type: "self",
          status: "draft",
        };
        const res = await fetch("/api/admin/maps", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        });
        if (!res.ok) {
          const err = await res.json().catch(() => ({ message: res.statusText }));
          throw new Error(err.message || `HTTP ${res.status}`);
        }
        const created = await res.json();
        rows[i] = { ...r, id: created.id, status: "created", error: undefined };
        cmds.push(`./scripts/tile_map.sh ${created.id} ${shellQuote(r.path)}`);
        cmds.push(`# ↑ ${r.name} (${r.year || "?"})`);
        okCount++;
      } catch (e: any) {
        rows[i] = { ...r, status: "failed", error: e.message };
        failCount++;
      }
    }
    rows = rows;

    cmds.push("");
    cmds.push("echo \"✓ All tiling jobs done.\"");
    resultScript = cmds.join("\n");
    createSummary = `${okCount} created · ${failCount} failed`;
    creating = false;
  }

  function shellQuote(s: string): string {
    return `'${s.replace(/'/g, "'\\''")}'`;
  }

  async function copyScript() {
    if (!resultScript) return;
    try { await navigator.clipboard.writeText(resultScript); } catch {}
  }

  // ── Bulk metadata refresh (set thumb + clean name) for created rows ────
  async function backfillCreated() {
    const created = rows.filter(r => r.id);
    for (const r of created) {
      try {
        const info = await fetch(`https://iiif.maparchive.vn/iiif/${r.id}/info.json`).then(x => x.ok ? x.json() : null);
        if (!info?.sizes?.length) continue;
        const last = info.sizes[info.sizes.length - 1];
        const thumb = `https://iiif.maparchive.vn/iiif/${r.id}/full/${last.width},${last.height}/0/default.jpg`;
        await fetch(`/api/admin/maps/${r.id}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ thumbnail: thumb, iiif_image: `https://iiif.maparchive.vn/iiif/${r.id}` }),
        });
      } catch {}
    }
    createSummary += " · thumbnails backfilled";
  }

  // ── Sync georef status from the Allmaps annotation server ───────────────
  let syncing = false;
  let syncResult: string | null = null;
  async function syncGeorefFromAllmaps() {
    syncing = true;
    syncResult = null;
    try {
      const res = await fetch('/api/admin/maps/sync-georef', { method: 'POST' });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.message || `HTTP ${res.status}`);
      syncResult = `Checked ${data.checked}, flipped ${data.flipped} to georef_done.`;
    } catch (e: any) {
      syncResult = `Failed: ${e.message}`;
    } finally {
      syncing = false;
    }
  }
</script>

<svelte:head><title>Bulk Upload — Admin</title></svelte:head>

<div class="page">
  <header class="hero">
    <a class="back-link" href="/catalog">← Catalog</a>
    <h1>Bulk Map Upload</h1>
    <p class="lede">Insert many maps at once. Tiling still runs locally — this page gives you the script.</p>
  </header>

  {#if !roleChecked}
    <p class="status">Checking access…</p>
  {:else if role !== "admin"}
    <p class="status error">Admin only.</p>
  {:else}
    <section class="panel">
      <h2>1. Defaults</h2>
      <label class="field">
        <span>Default collection</span>
        <input type="text" bind:value={defaultCollection} placeholder="e.g. Service Géographique de l'Indochine" />
      </label>
    </section>

    <section class="panel">
      <h2>2. Maps</h2>
      <p class="hint">Paste from a spreadsheet (one row per line, tab- or comma-separated: path, name, year, collection, map_type, location) — or just paste a list of paths and we'll auto-parse name/year from the filename.</p>
      <textarea
        rows="3"
        placeholder="/Users/you/maps/20 Ha Noi 1903.jpg&#10;/Users/you/maps/31 Hai Phong 1904.jpg"
        on:paste|preventDefault={(e) => { const t = e.clipboardData?.getData('text') ?? ''; parsePaste(t); }}
      ></textarea>

      <div class="grid-wrap">
        <table class="grid">
          <thead>
            <tr>
              <th style="width:32%">Local path</th>
              <th>Name</th>
              <th style="width:80px">Year</th>
              <th>Collection</th>
              <th style="width:120px">Map type</th>
              <th style="width:120px">Location</th>
              <th style="width:80px">Status</th>
              <th style="width:40px"></th>
            </tr>
          </thead>
          <tbody>
            {#each rows as row, i (i)}
              <tr class:row-ok={row.status === 'created'} class:row-bad={row.status === 'failed'}>
                <td><input type="text" bind:value={row.path} on:blur={() => applyAutoName(i)} placeholder="/abs/path/to/file.jpg" /></td>
                <td><input type="text" bind:value={row.name} /></td>
                <td><input type="text" bind:value={row.year} /></td>
                <td><input type="text" bind:value={row.collection} /></td>
                <td><input type="text" bind:value={row.map_type} /></td>
                <td><input type="text" bind:value={row.location} /></td>
                <td class="status-cell">
                  {#if row.status === 'created'}<span class="ok" title={row.id}>✓</span>
                  {:else if row.status === 'failed'}<span class="bad" title={row.error}>✗</span>
                  {:else}—{/if}
                </td>
                <td><button class="icon-btn" on:click={() => removeRow(i)} aria-label="Remove row">✕</button></td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>

      <div class="row-actions">
        <button class="pill-btn" on:click={addRow}>+ Add row</button>
        <button class="pill-btn" on:click={clearAll}>Clear all</button>
        <span class="grow"></span>
        <button class="action-btn primary-btn" on:click={createBatch} disabled={creating}>
          {creating ? 'Creating…' : `Create ${rows.length} map row${rows.length === 1 ? '' : 's'}`}
        </button>
      </div>
      {#if createSummary}<p class="status">{createSummary}</p>{/if}
    </section>

    <section class="panel">
      <h2>Sync georef status</h2>
      <p class="hint">Probe the Allmaps annotation server for every map with an <code>allmaps_id</code> but <code>georef_done = false</code>. Volunteers who finish georef in the Allmaps Editor become visible to /contribute/digitalize after this runs. Idempotent.</p>
      <div class="script-actions">
        <button class="pill-btn" on:click={syncGeorefFromAllmaps} disabled={syncing}>
          {syncing ? 'Syncing…' : 'Sync georef from Allmaps'}
        </button>
      </div>
      {#if syncResult}<p class="status">{syncResult}</p>{/if}
    </section>

    {#if resultScript}
      <section class="panel">
        <h2>3. Run this locally to tile + upload</h2>
        <p class="hint">Save as <code>tile_batch.sh</code> in your <code>svelte-beta</code> repo root, <code>chmod +x</code>, then run. After tiling, click the backfill button below to set IIIF URLs and thumbnails on the new map rows.</p>
        <div class="script-actions">
          <button class="pill-btn" on:click={copyScript}>📋 Copy script</button>
          <button class="pill-btn" on:click={backfillCreated}>Backfill thumbnails (after tiling)</button>
        </div>
        <pre class="script">{resultScript}</pre>
      </section>
    {/if}
  {/if}
</div>

<style>
  .page { max-width: 1200px; margin: 0 auto; padding: 2rem 1.5rem 4rem; font-family: var(--font-sans, system-ui, sans-serif); }
  .hero { margin-bottom: 2rem; }
  .back-link { color: var(--color-text-muted, #555); text-decoration: none; font-size: 0.85rem; }
  .back-link:hover { text-decoration: underline; }
  h1 { font-family: 'Space Grotesk', sans-serif; font-size: 2.25rem; font-weight: 800; margin: 0.5rem 0 0.25rem; }
  .lede { color: var(--color-text-muted, #555); margin: 0; }

  .panel { background: #fff; border: 2px solid #111; box-shadow: 5px 5px 0 #111; padding: 1.5rem; margin-bottom: 1.5rem; }
  .panel h2 { font-family: 'Space Grotesk', sans-serif; font-size: 1.1rem; margin: 0 0 1rem; }
  .panel .hint { color: var(--color-text-muted, #555); font-size: 0.85rem; margin: 0 0 0.75rem; }

  .field { display: block; margin-bottom: 0.75rem; }
  .field span { display: block; font-size: 0.8rem; font-weight: 600; margin-bottom: 0.25rem; }
  .field input, textarea, .grid input { width: 100%; padding: 0.45rem 0.6rem; border: 1.5px solid #111; border-radius: 4px; font: inherit; font-size: 0.85rem; box-sizing: border-box; background: #fff; }
  textarea { font-family: ui-monospace, Menlo, monospace; font-size: 0.78rem; margin-bottom: 1rem; }

  .grid-wrap { overflow-x: auto; border: 1.5px solid #111; }
  .grid { width: 100%; border-collapse: collapse; font-size: 0.78rem; }
  .grid th { text-align: left; background: #f5f5f0; padding: 0.5rem 0.6rem; border-bottom: 1.5px solid #111; font-weight: 700; }
  .grid td { padding: 0.25rem 0.3rem; border-bottom: 1px solid #ddd; }
  .grid input { border: 1px solid transparent; padding: 0.3rem 0.5rem; }
  .grid input:focus { border-color: #111; outline: none; }
  .grid .row-ok { background: #f0fdf4; }
  .grid .row-bad { background: #fef2f2; }
  .status-cell { text-align: center; font-weight: 700; }
  .status-cell .ok { color: #16a34a; }
  .status-cell .bad { color: #dc2626; }
  .icon-btn { background: none; border: none; cursor: pointer; color: #555; font-size: 0.9rem; padding: 0.3rem; }
  .icon-btn:hover { color: #dc2626; }

  .row-actions { display: flex; align-items: center; gap: 0.5rem; margin-top: 1rem; }
  .row-actions .grow { flex: 1; }

  .script-actions { display: flex; gap: 0.5rem; margin-bottom: 0.75rem; }
  .script { background: #0f1115; color: #e5e7eb; padding: 1rem; border-radius: 4px; overflow-x: auto; font-family: ui-monospace, Menlo, monospace; font-size: 0.78rem; line-height: 1.45; }

  .status { font-size: 0.85rem; }
  .status.error { color: #dc2626; }
</style>
